export const LOAGING_STATUS = 'LOAGING_STATUS'
export const SET_NEW_FOLDER = 'SET_NEW_FOLDER'
export const SET_DRAG_TABLE_DATA = 'SET_DRAG_TABLE_DATA'

// 报表(dashboard)
export const SET_FOlDERS = 'SET_FOlDERS'
export const SET_REPORT_LIST = 'SET_REPORT_LIST'
export const SET_NEW_REPORT = 'SET_NEW_REPORT'
export const SET_CHARTS = 'SET_CHARTS'
export const SET_CURRENT_DASH = 'SET_CURRENT_DASH'
export const SET_SELECT_REPORT = 'SET_SELECT_REPORT'

export const SET_FOlDERS_REPORT = 'SET_FOlDERS_REPORT'
export const SET_DELETE_LAYER = 'SET_DELETE_LAYER'
export const SET_RENAME_FOLDERID = 'SET_RENAME_FOLDERID'
export const SET_GRIDSTER = 'SET_GRIDSTER'


// 数据源(datasource)
export const SET_ACTIVE_DATASOURCE = 'SET_ACTIVE_DATASOURCE'
export const SET_ACTIVE_TABlE = 'SET_ACTIVE_TABlE'

// 工作表(worksheet)
export const SET_TABLE_DATA = 'SET_TABLE_DATA'
export const SET_SHEET_ELEMENT = 'SET_SHEET_ELEMENT'
export const SET_ACTIVE_SHEET = 'SET_ACTIVE_SHEET'
export const SET_CONDITIONS = 'SET_CONDITIONS'